services:
  - type: web
    name: ml-dl-api
    runtime: docker
    dockerfilePath: ./MLOps/model-deployment/Dockerfile
    dockerContext: ./MLOps/model-deployment
    plan: free
    healthCheckPath: /health
